<a href="https://colab.research.google.com/github/sravs1407/computational_statistics/blob/main/discriminent_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from scipy import  stats
import scipy.stats
import numpy as np

In [51]:
sat=np.asarray([1300,1260,1220,1180,1060,1140,1100,1020,980,940])
gpa=np.asarray([2.7,3.7,2.9,2.5,3.9,2.1,3.5,3.3,2.3,3.1])
grad=["yes","yes","yes","yes","yes","no","no","no","no","no"]
l=[1,1,1,1,1,1,1,1,1,1]
for i in range(len(grad)):
  if grad[i]=="yes":
    grad[i]=1
  else:
    grad[i]=0
y=np.matrix(grad)
l=np.asarray(l)
x=[sat,gpa]
x.insert(0,l)
x_t=np.matrix(x)
x=np.transpose(x)
y=np.transpose(y)
print(y,x)
xtx=np.matmul(x_t,x)
xty=np.matmul(x_t,y)
xtxinv=np.linalg.inv(xtx)
b=np.matmul(xtxinv,xty)
print(b)
print("y=",b[0],"+",b[1],"*sat+",b[2],"*gpa")

[[1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]] [[1.00e+00 1.30e+03 2.70e+00]
 [1.00e+00 1.26e+03 3.70e+00]
 [1.00e+00 1.22e+03 2.90e+00]
 [1.00e+00 1.18e+03 2.50e+00]
 [1.00e+00 1.06e+03 3.90e+00]
 [1.00e+00 1.14e+03 2.10e+00]
 [1.00e+00 1.10e+03 3.50e+00]
 [1.00e+00 1.02e+03 3.30e+00]
 [1.00e+00 9.80e+02 2.30e+00]
 [1.00e+00 9.40e+02 3.10e+00]]
[[-3.83919635e+00]
 [ 3.23263173e-03]
 [ 2.39549603e-01]]
y= [[-3.83919635]] + [[0.00323263]] *sat+ [[0.2395496]] *gpa


In [56]:
s=1000
g=2.9
y1=b[0]+b[1]*s+b[2]*g
print(y1)
if y1>0.5:
  print("incoming candidate is graduated")
else:
  print("incoming candidate is not graduated")

[[0.08812923]]
incoming candidate is not graduated
