<a href="https://colab.research.google.com/github/sravs1407/computational_statistics/blob/main/discriminent_analysis(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [19]:
cur=[2.95,2.53,3.57,3.16,2.58,2.16,3.27]
dia=[6.63,7.79,5.65,5.47,4.46,6.22,3.52]
qua=["passed","passed","passed","passed","not passed","not passed","not passed"]
for i in range(len(qua)):
  if qua[i]=="passed":
    qua[i]=1
  else:
    qua[i]=2
print(qua)
x_t=[cur,dia]
x_t=np.asarray(x_t)
print(x_t)
x=np.transpose(x_t)
print(x)
meanx=[np.mean(x_t[0]),np.mean(x_t[1])]
print(meanx)
x1=[]
x2=[]
for i in range(len(qua)):
  if qua[i]==1:
    x1.append([cur[i],dia[i]])
  else:
    x2.append([cur[i],dia[i]])
x1=np.asarray(x1)
x2=np.asarray(x2)
print(x1,x2)
x1_t=np.transpose(x1)
x2_t=np.transpose(x2)
print(x1_t)
meanx1=[np.mean(x1_t[0]),np.mean(x1_t[1])]
meanx2=[np.mean(x2_t[0]),np.mean(x2_t[1])]
print(meanx1)
print(meanx2)

[1, 1, 1, 1, 2, 2, 2]
[[2.95 2.53 3.57 3.16 2.58 2.16 3.27]
 [6.63 7.79 5.65 5.47 4.46 6.22 3.52]]
[[2.95 6.63]
 [2.53 7.79]
 [3.57 5.65]
 [3.16 5.47]
 [2.58 4.46]
 [2.16 6.22]
 [3.27 3.52]]
[2.888571428571429, 5.677142857142857]
[[2.95 6.63]
 [2.53 7.79]
 [3.57 5.65]
 [3.16 5.47]] [[2.58 4.46]
 [2.16 6.22]
 [3.27 3.52]]
[[2.95 2.53 3.57 3.16]
 [6.63 7.79 5.65 5.47]]
[3.0525, 6.385]
[2.67, 4.733333333333333]


In [32]:
xsubu=[]
for i in range(len(cur)):
  xsubu.append([x_t[0][i]-meanx[0],x_t[1][i]-meanx[1]])
xsubu=np.asarray(xsubu)
print(xsubu)
mat=np.matrix(xsubu)
print(mat)
num=np.matmul(np.transpose(mat),mat)
c=num/len(cur)
print(c)
cinv=np.linalg.inv(c)
print(cinv)

[[ 0.06142857  0.95285714]
 [-0.35857143  2.11285714]
 [ 0.68142857 -0.02714286]
 [ 0.27142857 -0.20714286]
 [-0.30857143 -1.21714286]
 [-0.72857143  0.54285714]
 [ 0.38142857 -2.15714286]]
[[ 0.06142857  0.95285714]
 [-0.35857143  2.11285714]
 [ 0.68142857 -0.02714286]
 [ 0.27142857 -0.20714286]
 [-0.30857143 -1.21714286]
 [-0.72857143  0.54285714]
 [ 0.38142857 -2.15714286]]
[[ 0.20598367 -0.23093265]
 [-0.23093265  1.69216327]]
[[5.73171449 0.78221769]
 [0.78221769 0.69771022]]


In [40]:
#f1
mmeanx1=np.matrix(meanx1)
mmeanx2=np.matrix(meanx2)
xk=np.matrix([2.8,5.46])
p1=np.matmul(np.matmul(mmeanx1,cinv),np.transpose(xk))
p2=np.matmul(np.matmul(mmeanx1,cinv),np.transpose(mmeanx1))
p2=p2/2
print(p1-p2)
import math
f1=p1-p2+math.log(len(x1)/len(x))
print(f1)

[[44.1628916]]
[[43.60327581]]


In [41]:
#f2
p3=np.matmul(np.matmul(mmeanx2,cinv),np.transpose(xk))
p4=np.matmul(np.matmul(mmeanx2,cinv),np.transpose(mmeanx2))
p4=p4/2
f2=p3-p4+math.log(len(x2)/len(x))
print(f2)

[[43.67295843]]


In [42]:
if f2>f1:
  print("new record goes to second group")
else:
  print("new record goes to first group")

new record goes to second group
